version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: task_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasknet

  redis:
    image: redis:7
    container_name: task_redis
    ports:
      - "6379:6379"
    networks:
      - tasknet

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: task_zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - tasknet

  kafka:
    image: bitnami/kafka:latest
    container_name: task_kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - tasknet

  backend:
    build: ./backend
    container_name: task_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - tasknet

  frontend:
    build: ./frontend
    container_name: task_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tasknet

volumes:
  pgdata:

networks:
  tasknet:
