server:
  port: 8085

spring:
  application:
    name: task-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:taskdb}
    driver-class-name: ${DATASOURCE_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
  kafka:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyForJWTTokenGenerationAndValidation2024!}
  expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/taskdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:platformuser}
    password: ${DB_PASSWORD:platformpass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: kubernetes
  datasource:
    url: jdbc:postgresql://postgres-service:5432/taskdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:platformuser}
    password: ${DB_PASSWORD:platformpass}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  kafka:
    enabled: true
    bootstrap-servers: ${KAFKA_SERVICE_HOST:localhost}:${KAFKA_SERVICE_PORT:9092}
    consumer:
      group-id: task-api-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/task-api}
