declare module 'lucide-react' {
  import type { FC, SVGProps } from 'react';
  type IconProps = { size?: number | string; color?: string; strokeWidth?: number | string; className?: string } & SVGProps<SVGSVGElement>;
  export const LayoutDashboard: FC<IconProps>;
  export const Users: FC<IconProps>;
  export const Activity: FC<IconProps>;
  export const Store: FC<IconProps>;
  export const BarChart3: FC<IconProps>;
  export const LogOut: FC<IconProps>;
  export const LogIn: FC<IconProps>;
  export const Search: FC<IconProps>;
  export const Filter: FC<IconProps>;
  export const UserCheck: FC<IconProps>;
  export const UserX: FC<IconProps>;
  export const Eye: FC<IconProps>;
  export const Edit2: FC<IconProps>;
  export const Clock: FC<IconProps>;
  export const AlertTriangle: FC<IconProps>;
  export const CheckCircle: FC<IconProps>;
  export const ArrowRight: FC<IconProps>;
  export const ExternalLink: FC<IconProps>;
  export const ChevronLeft: FC<IconProps>;
  export const ChevronRight: FC<IconProps>;
  export const History: FC<IconProps>;
  export const ShoppingBag: FC<IconProps>;
  export const Hotel: FC<IconProps>;
  export const UtensilsCrossed: FC<IconProps>;
  export const UserPlus: FC<IconProps>;
  export const Shield: FC<IconProps>;
  export const Trash2: FC<IconProps>;
  export const X: FC<IconProps>;
  export const Database: FC<IconProps>;
  export const Plus: FC<IconProps>;
  export const ChevronRight: FC<IconProps>;
  export type LucideIcon = FC<IconProps>;
}
