
# name: CI

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:16
#         env:
#           POSTGRES_DB: taskdb
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#         ports:
#           - 5432:5432
#       redis:
#         image: redis:7
#         ports:
#           - 6379:6379
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           distribution: temurin
#           java-version: '17'
#       - name: Build with Maven
#         run: mvn -B -DskipTests=false test package
